[source.crates-io]
replace-with = 'tuna-sparse'

[source.tuna-sparse]
registry = "sparse+https://mirrors.tuna.tsinghua.edu.cn/crates.io-index/"

[net]
# 如果 Git 遇到问题，可以使用系统自带的 git cli
git-fetch-with-cli = true
